spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    change-log: db/changelog/changelog-main.xml
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers=true:
