spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers=true:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    change-log: db/changelog/changelog-main.xml
  security:
    jwt:
      secret: ${JWT_SECRET_PHRASE:defaultjwtsecretphrase111defaultjwtsecretphrase222defaultjwtsecretphrase333}
      expired: 3600000
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
