package by.mikhalevich.grandcapitaltesttask.dao.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;

import java.util.Objects;

/**
 * @author Alex Mikhalevich
 * @created 2025-04-25 15:36
 */

@Entity
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "EMAIL_DATA")
public class EmailData {

    /**
     * Technical identifier of user's email data in database. Generated by incremental strategy
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID")
    private Long id;

    /**
     * User
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "USER_ID")
    private User user;

    /**
     * Email itself
     */
    @Column(name = "EMAIL")
    private String email;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EmailData emailData)) return false;
        return Objects.equals(user, emailData.user) && Objects.equals(email, emailData.email);
    }

    @Override
    public int hashCode() {
        return Objects.hash(user, email);
    }

    @Override
    public String toString() {
        return "EmailData{" +
                "id=" + id +
                ", user=" + user +
                ", email='" + email + '\'' +
                '}';
    }
}
