package by.mikhalevich.grandcapitaltesttask.dao.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;

import java.util.Objects;

/**
 * @author Alex Mikhalevich
 * @created 2025-04-25 16:02
 */

@Entity
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "PHONE_DATA")
public class PhoneData {

    /**
     * Technical identifier of user's phone data in database. Generated by incremental strategy
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID")
    private Long id;

    /**
     * User
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "USER_ID")
    private User user;

    /**
     * Phone itself, format 79207865432
     */
    @Column(name = "PHONE")
    private String phone;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof PhoneData phoneData)) return false;
        return Objects.equals(user, phoneData.user) && Objects.equals(phone, phoneData.phone);
    }

    @Override
    public int hashCode() {
        return Objects.hash(user, phone);
    }

    @Override
    public String toString() {
        return "PhoneData{" +
                "id=" + id +
                ", user=" + user +
                ", phone='" + phone + '\'' +
                '}';
    }
}
