package by.mikhalevich.grandcapitaltesttask.dao.model;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.util.List;
import java.util.Objects;

/**
 * @author Alex Mikhalevich
 * @created 2025-04-25 15:18
 */

@Entity
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "USER")
public class User {

    /**
     * Technical identifier of a user, PK in database. Generated by incremental strategy
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID")
    private Long id;

    /**
     * User's name
     */
    @Column(name = "NAME")
    private String name;

    /**
     * User's date of birth, format dd.mm.yyyy
     */
    @Column(name = "DATE_OF_BIRTH")
    private LocalDate dateOfBirth;

    /**
     * User's password, min length 8, max 500
     */
    @Column(name = "PASSWORD")
    private String password;

    /**
     * User's email data
     */
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    private List<EmailData> emailData;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof User user)) return false;
        return Objects.equals(name, user.name) && Objects.equals(dateOfBirth, user.dateOfBirth)
                && Objects.equals(password, user.password) && Objects.equals(emailData, user.emailData);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, dateOfBirth, password, emailData);
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", dateOfBirth=" + dateOfBirth +
                ", password='" + password + '\'' +
                ", emailData=" + emailData +
                '}';
    }
}
